import { ThemeProvider } from 'styled-components'
import {theme} from '../styles/theme'
import { useApollo } from "../apollo";
import { ApolloProvider } from '@apollo/client';
import { GlobalStyles } from '@/styles/global-styles';
import Head from 'next/head';

function MyApp({ Component, pageProps, ...rest }) {
  const client = useApollo();

  return (
    <>
      <Head>
        <title>Theme1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <GlobalStyles />
        <ApolloProvider client={client}>
          <Component {...pageProps} {...rest }/>  
        </ApolloProvider>
      </ThemeProvider>
    </>
  )
}

export default MyApp